// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9N9Mr4nGiBuv2HvEs9HGcizyVoE6wlWI',
    appId: '1:626371745923:web:c4fafb3652ecb676ec23b6',
    messagingSenderId: '626371745923',
    projectId: 'pocketlawyer-ai-2025',
    authDomain: 'pocketlawyer-ai-2025.firebaseapp.com',
    storageBucket: 'pocketlawyer-ai-2025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApPzdx-HgynKrVJGZO_jWNi3UG2vJxL2k',
    appId: '1:626371745923:android:4e1fe4c0a6babe32ec23b6',
    messagingSenderId: '626371745923',
    projectId: 'pocketlawyer-ai-2025',
    storageBucket: 'pocketlawyer-ai-2025.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9N9Mr4nGiBuv2HvEs9HGcizyVoE6wlWI',
    appId: '1:626371745923:web:bd9842255b6a2330ec23b6',
    messagingSenderId: '626371745923',
    projectId: 'pocketlawyer-ai-2025',
    authDomain: 'pocketlawyer-ai-2025.firebaseapp.com',
    storageBucket: 'pocketlawyer-ai-2025.firebasestorage.app',
  );

}