type User @table {
  displayName: String!
  email: String!
  createdAt: Timestamp!
  photoUrl: String
  lastLogin: Timestamp
}

type DocumentTemplate @table {
  name: String!
  type: String!
  contentSchema: String!
  createdAt: Timestamp!
  description: String
  category: String
}

type UserDocument @table {
  title: String!
  documentType: String!
  storageUrl: String!
  createdAt: Timestamp!
  updatedAt: Timestamp!
  user: User
  category: String
  tags: [String]
  isSensitive: Boolean
  generatedData: String
}

type LegalTopic @table {
  name: String!
  createdAt: Timestamp!
  description: String
  keywords: [String]
}

type LegalArticle @table {
  title: String!
  content: String!
  createdAt: Timestamp!
  updatedAt: Timestamp!
  legalTopic: LegalTopic
  sourceUrl: String
  isPublic: Boolean
}